name: test_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0

  riverpod_annotation: ^2.1.6
  hooks_riverpod: ^2.4.1
  flutter_riverpod: ^2.4.1
  cupertino_icons: ^1.0.6

  fast_immutable_collections: ^9.1.5
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  random_name_generator: ^1.3.0
  drift_db_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  drift_dev: ^2.12.1

flutter:
  uses-material-design: true
